
import os
import psycopg2
import psycopg2.extras
from prettytable import PrettyTable
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py


def query():
    load_dotenv()

    user = os.getenv('USERNAMEZ')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor, host='127.0.0.1', port='5432')
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    class MFStruct:
        cust = ""
        sum_1_quant = 0
        avg_1_quant_sum = 0
        avg_1_quant_count = 0
        avg_1_quant = 0
        max_1_quant = -1
        min_1_quant = float('inf')
        count_1_quant = 0
        sum_2_quant = 0
        avg_2_quant_sum = 0
        avg_2_quant_count = 0
        avg_2_quant = 0
        max_2_quant = -1
        min_2_quant = float('inf')
        count_2_quant = 0

    data = []
    
    # For all the grouping variables
    group_by_map = dict()
    
    for row in cur:
        key = (row.get('cust'))
        
        if (not group_by_map.get(key)) and (group_by_map.get(key) != 0):
            data.append(MFStruct())
            group_by_map[key] = len(data) - 1
        
        pos = group_by_map.get(key)
        data[pos].cust = row.get('cust')

    # We need to compute values to the aggregate functions with their corresponding grouping variable predicate.
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='NY' and row.get('cust')==cust:
                data[pos].sum_1_quant += row.get('quant')
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='NY' and row.get('cust')==cust:
                data[pos].avg_1_quant_sum += row.get('quant')
                data[pos].avg_1_quant_count += 1

                if data[pos].avg_1_quant_count != 0:
                    data[pos].avg_1_quant = data[pos].avg_1_quant_sum / data[pos].avg_1_quant_count
                else:
                    data[pos].avg_1_quant = 'Infinity'
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='NY' and row.get('cust')==cust:
                data[pos].max_1_quant = max(data[pos].max_1_quant, row.get('quant'))
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='NY' and row.get('cust')==cust:
                data[pos].min_1_quant = min(data[pos].min_1_quant, row.get('quant'))
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='NY' and row.get('cust')==cust:
                data[pos].count_1_quant += 1
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='CT' and row.get('cust')==cust:
                data[pos].sum_2_quant += row.get('quant')
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='CT' and row.get('cust')==cust:
                data[pos].avg_2_quant_sum += row.get('quant')
                data[pos].avg_2_quant_count += 1

                if data[pos].avg_2_quant_count != 0:
                    data[pos].avg_2_quant = data[pos].avg_2_quant_sum / data[pos].avg_2_quant_count
                else:
                    data[pos].avg_2_quant = 'Infinity'
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='CT' and row.get('cust')==cust:
                data[pos].max_2_quant = max(data[pos].max_2_quant, row.get('quant'))
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='CT' and row.get('cust')==cust:
                data[pos].min_2_quant = min(data[pos].min_2_quant, row.get('quant'))
    cur.scroll(0, mode='absolute')

    for row in cur:
        for pos in range(len(data)):
            cust = data[pos].cust
            sum_1_quant = data[pos].sum_1_quant
            avg_1_quant = data[pos].avg_1_quant
            max_1_quant = data[pos].max_1_quant
            min_1_quant = data[pos].min_1_quant
            count_1_quant = data[pos].count_1_quant
            sum_2_quant = data[pos].sum_2_quant
            avg_2_quant = data[pos].avg_2_quant
            max_2_quant = data[pos].max_2_quant
            min_2_quant = data[pos].min_2_quant
            count_2_quant = data[pos].count_2_quant

            if row.get('state')=='CT' and row.get('cust')==cust:
                data[pos].count_2_quant += 1

    # Apply HAVING clause if present


    operations_dict = {'cust': {'found': False}, 'sum_1_quant': {'found': False}, 'avg_1_quant': {'found': False}, 'max_1_quant': {'found': False}, 'min_1_quant': {'found': False}, 'count_1_quant': {'found': False}, 'sum_2_quant': {'found': False}, 'avg_2_quant': {'found': False}, 'max_2_quant': {'found': False}, 'min_2_quant': {'found': False}, 'count_2_quant': {'found': False}}
    table = PrettyTable()
    table.field_names = ['cust', 'sum_1_quant', 'avg_1_quant', 'max_1_quant', 'min_1_quant', 'count_1_quant', 'sum_2_quant', 'avg_2_quant', 'max_2_quant', 'min_2_quant', 'count_2_quant']
    
    for obj in data:
        temp = []
        
        for j in table.field_names:
            if not operations_dict[j]['found']:
                temp.append(getattr(obj, j))
            else:
                if not (operations_dict[j]['operand1'].isnumeric() or operations_dict[j]['operand2'].isnumeric()):
                    value = eval(f"{getattr(obj, operations_dict[j]['operand1'])} {operations_dict[j]['operator']} {getattr(obj, operations_dict[j]['operand2'])}")
                    temp.append(value)
                else:
                    is_1_int = True if operations_dict[j]['operand1'].isnumeric() else False
                    is_2_int = True if operations_dict[j]['operand2'].isnumeric() else False
                    int_expr = f"{operations_dict[j]['operand1']} {operations_dict[j]['operator']} {getattr(obj, operations_dict[j]['operand2'])}" if is_1_int else f"{getattr(obj, operations_dict[j]['operand1'])} {operations_dict[j]['operator']} {operations_dict[j]['operand2']}"
                    value = eval(int_expr)
                    temp.append(value)
        table.add_row(temp)

    # Printing the table
    return table

    
if "__main__" == __name__:
    print(query())
    